// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDto4h4e7lSKkxTxRjwa5xzE8TzPDE_ipU',
    appId: '1:349377265203:web:db53fb6a217bc6f8006d46',
    messagingSenderId: '349377265203',
    projectId: 'leaderboard-47576',
    authDomain: 'leaderboard-47576.firebaseapp.com',
    storageBucket: 'leaderboard-47576.appspot.com',
    measurementId: 'G-2DPDE9ZQP1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXfStRg0fxr9xyUbPJvAdkzgfH8Q0oXf0',
    appId: '1:349377265203:android:2260d273eaffc231006d46',
    messagingSenderId: '349377265203',
    projectId: 'leaderboard-47576',
    storageBucket: 'leaderboard-47576.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJvX_v8khP7vo0Dk0mHc3jdRmCUbOlD4I',
    appId: '1:349377265203:ios:4a46af22d3b50ade006d46',
    messagingSenderId: '349377265203',
    projectId: 'leaderboard-47576',
    storageBucket: 'leaderboard-47576.appspot.com',
    iosClientId: '349377265203-i6t4f6903t5at879qspc13s126lagmvt.apps.googleusercontent.com',
    iosBundleId: 'com.example.leaderboardApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJvX_v8khP7vo0Dk0mHc3jdRmCUbOlD4I',
    appId: '1:349377265203:ios:4a46af22d3b50ade006d46',
    messagingSenderId: '349377265203',
    projectId: 'leaderboard-47576',
    storageBucket: 'leaderboard-47576.appspot.com',
    iosClientId: '349377265203-i6t4f6903t5at879qspc13s126lagmvt.apps.googleusercontent.com',
    iosBundleId: 'com.example.leaderboardApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDto4h4e7lSKkxTxRjwa5xzE8TzPDE_ipU',
    appId: '1:349377265203:web:b08632b31a7ad7b9006d46',
    messagingSenderId: '349377265203',
    projectId: 'leaderboard-47576',
    authDomain: 'leaderboard-47576.firebaseapp.com',
    storageBucket: 'leaderboard-47576.appspot.com',
    measurementId: 'G-G7D6D1TVC6',
  );
}
